---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  selector:
    matchLabels:
      api: web-api
  replicas: 1
  template:
    metadata:
      labels:
        app: web-api
        api: web-api
    spec:
      containers:
        - name: web-api
          image: seaweedfs-web-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "files_db"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: SEAWEED_MASTER_URL
              value: "http://seaweedfs-master:9333/dir/"
          ports:
            - name: web-api
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: web-api
  selector:
    app: web-api
  type: ClusterIP
